version: '3.7'

networks:
  traefik:
    external: true
    name: traefik

services:

  whoami4:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    
    networks:
      - traefik

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.port=80"

      # Define the URL to access this app
      - "traefik.http.routers.whoami4.rule=Host(`whoami4.${DOMAINNAME}`)"

      # Access via HTTP and HTTPS
      #- "traefik.http.routers.whoami4.entrypoints=websecure"
      - "traefik.http.routers.whoami4.entrypoints=web"

      # Forward authentication to keycloak for logon
      #- "traefik.http.routers.whoami4.middlewares=keycloakForwardAuth@docker"
    

      # The application (i.e. this container)
      - "traefik.http.routers.whoami4.service=whoami4"
      - "traefik.http.services.whoami4.loadbalancer.server.port=80"
